name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    if: (!contains(github.event.head_commit.message, 'ci(release)'))
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - if: github.event.pull_request
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: node-modules
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-modules
          restore-keys: ${{ runner.os }}-node-modules

      - uses: actions/setup-node@v2
        with:
          node-version: 12.14
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --non-interactive --no-progress

      - name: Bootstrap packages
        run: yarn bootstrap:packages

      - name: Run CI scripts
        run: yarn ci
